---

# Last updated to 1.9.1

require:
  - 'rubocop-performance'

################################################################################
#                                PERFORMANCE
################################################################################

Performance/AncestorsInclude:
  Enabled:                                    true

# Mistakenly created: https://github.com/rubocop-hq/rubocop-performance/pull/199/files
Performance/ArraySemiInfiniteRangeSlice:
  Enabled:                                    false

Performance/BigDecimalWithNumericArgument:
  Enabled:                                    true

Performance/BindCall:
  Enabled:                                    true

Performance/BlockGivenWithExplicitBlock:
  Enabled:                                    true

Performance/Caller:
  Enabled:                                    true

Performance/Casecmp:
  Enabled:                                    true

Performance/CaseWhenSplat:
  Enabled:                                    true

Performance/ChainArrayAllocation:
  Enabled:                                    true

Performance/CollectionLiteralInLoop:
  Enabled:                                    true
  MinSize:                                    1
  Exclude:
    - '**/spec/**/*.rb'

Performance/CompareWithBlock:
  Enabled:                                    true

Performance/ConstantRegexp:
  Enabled:                                    true

Performance/Count:
  Enabled:                                    true

Performance/DeletePrefix:
  Enabled:                                    true

Performance/DeleteSuffix:
  Enabled:                                    true

Performance/Detect:
  Enabled:                                    true

Performance/DoubleStartEndWith:
  Enabled:                                    true
  IncludeActiveSupportAliases:                true

Performance/EndWith:
  Enabled:                                    true

Performance/FixedSize:
  Enabled:                                    true

Performance/FlatMap:
  Enabled:                                    true

Performance/InefficientHashSearch:
  Enabled:                                    true

Performance/IoReadlines:
  Enabled:                                    true

Performance/MethodObjectAsBlock:
  Enabled:                                    true

Performance/OpenStruct:
  Enabled:                                    true
  Exclude:
    - '**/spec/**/*.rb'

Performance/RangeInclude:
  Enabled:                                    true

Performance/RedundantBlockCall:
  Enabled:                                    true

Performance/RedundantMatch:
  Enabled:                                    true

Performance/RedundantMerge:
  Enabled:                                    true

Performance/RedundantSortBlock:
  Enabled:                                    true

Performance/RedundantStringChars:
  Enabled:                                    true

Performance/RegexpMatch:
  Enabled:                                    true

Performance/ReverseEach:
  Enabled:                                    true

Performance/ReverseFirst:
  Enabled:                                    true

Performance/Size:
  Enabled:                                    true

Performance/SortReverse:
  Enabled:                                    true

Performance/Squeeze:
  Enabled:                                    true

Performance/StartWith:
  Enabled:                                    true

Performance/StringInclude:
  Enabled:                                    true

Performance/StringReplacement:
  Enabled:                                    true

Performance/Sum:
  Enabled:                                    true

Performance/TimesMap:
  Enabled:                                    true
  AutoCorrect:                                true

Performance/UnfreezeString:
  Enabled:                                    true

Performance/UriDefaultParser:
  Enabled:                                    true
