# frozen_string_literal: true

source 'https://rubygems.org'

group :console do
  gem 'awesome_print', '~> 1.6'
end

gem 'ruby-prof', '~> 1.6', :platforms => :mri_20,
                           :group     => :development

gemspec :name => 'ruby-progressbar'
